---
- name: Install Packages | Debian
  apt:
    update_cache: yes
    cache_valid: 3600.
    name: "{{ item }}"
    state: latest
  with_items:
    - libapache2-mod-php5
    - php5-cli
    - php5-mysql
    - php5-gd
    - php5-mcrypt
    - php5-json
    - php-pear
    - snmp
    - fping
    - mysql-server
    - mysql-client
    - python-mysqldb
    - rrdtool
    - subversion
    - whois
    - mtr-tiny
    - ipmitool
    - graphviz
    - imagemagick
    - libvirt-bin

